version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: springboot-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/watchstackdb
      SPRING_DATASOURCE_USERNAME: admindb
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: watchstackdb
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: